version: '2'

services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    depends_on:
      - db  # Add this line to ensure the app waits for the database
    networks:
      - yii2-network

  db:
    image: mysql:5.7
    container_name: yii2-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: yii2db
      MYSQL_USER: yii2user
      MYSQL_PASSWORD: yii2password
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - yii2-network

networks:
  yii2-network:

volumes:
  dbdata:
